name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ github.repository }}
          echo "New issue: ${{ github.event.issue.title }}"
          echo "Captured token: $GITHUB_TOKEN"


      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.12

      - name: Run linter
        shell: bash
        run: uv run -- pre-commit run -a
